name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar via SSH e atualizar servidor na AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Acessa a pasta do projeto
            cd /home/ubuntu/safenav
            
            # Puxa o código atualizado
            git pull origin main
            
            # Reinicia o Nginx
            sudo systemctl restart nginx
            
            # Encerra o processo antigo do Gunicorn na memória (o '|| true' evita falhas se o processo já estiver parado)
            pkill gunicorn || true
            
            # Ativa o ambiente virtual e sobe a nova versão do Gunicorn em segundo plano
            source venv/bin/activate
            gunicorn --bind 127.0.0.1:8000 safenav_project.wsgi:application --daemon